### ISSUE TITLE
Is version 0.13 published on NPM?

### ISSUE THREAD

**Issue by PunkDog** [angular/in-memory-web-api#11]
I can't see it on NPM. I'm getting warnings during the installation of packages:

npm WARN angular2-in-memory-web-api@0.0.12 requires a peer of @angular/core@2.0.0-rc.2 but none was installed.
npm WARN angular2-in-memory-web-api@0.0.12 requires a peer of @angular/http@2.0.0-rc.2 but none was installed.

**Comment by filipesilva** [comment]
Duplicate of https://github.com/angular/in-memory-web-api/issues/10
