### ISSUE TITLE
Add an option to prevent the content wrapped in the data property

### ISSUE THREAD

**Issue by asnowwolf** [angular/in-memory-web-api#112]
Add an option to prevent the content wrapped in the data property, because many real back-end server does not use the data property to wrap content, with this option, we can make it more easier.

**Comment by brendanmckeown** [comment]
You can modify the response body through the `responseInterceptor` method, which you add to your class that implements `InMemoryDbService`. 

Here is how I am using that method to remove the `data` property in the response:
```
import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryApiService implements InMemoryDbService {
  
  createDb(): any {
    // ...
  }

  responseInterceptor(responseOptions: any, requestInfo: any): any {
    let responseBody = responseOptions.body.data;
    responseOptions.body = responseBody;
    return responseOptions;
  }

}

```

**Comment by asnowwolf** [comment]
Sure, It works. But I think it's better to add a simple option because it's a common case.

**Comment by wardbell** [comment]
Incorporated this idea within PR #130 which will merge "soon"
