### ISSUE TITLE
support ES7 async for createDb

### ISSUE THREAD

**Issue by xmlking** [angular/in-memory-web-api#113]
I want to load initial data from `assets/data` and take advantage `in-memory-web-api`  features. 
please support `async` functions. 
```ts
@Injectable()
export class InMemoryDataService implements InMemoryDbService {
  async createDb() {
    const accounts = [
      { id: 1, name: 'Windstorm' },
      { id: 2, name: 'Bombasto' },
      { id: 3, name: 'Magneta' },
      { id: 4, name: 'Tornado' },
      { id: 5, name: 'Superman'},
      { id: 6, name: 'Batman'},
      { id: 7, name: 'BatGirl'},
      { id: 8, name: 'Robin'},
      { id: 9, name: 'Flash'},
      { id: 10, name: 'Bombasto' },
      { id: 11, name: 'Magneta' },
      { id: 12, name: 'Tornado' },
      { id: 13, name: 'Windstorm' },
      { id: 14, name: 'Bombasto' },
      { id: 15, name: 'Magneta' },
      { id: 16, name: 'Tornado' },
      { id: 17, name: 'Windstorm' },
      { id: 18, name: 'Bombasto' },
      { id: 19, name: 'Magneta' },
      { id: 20, name: 'Tornado' }
    ];
    const response = await fetch('assets/data/company.json');
    const companies = await response.json();
    console.log('companies', companies);
    return {accounts, companies};
  }
```

**Workaround** 
```
let companies
(async () => {
  const response = await fetch('assets/data/company.json');
  companies = await response.json();
  console.log('companies', companies);
})();

@Injectable()
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const accounts = [
      { id: 1, name: 'Windstorm' },
      { id: 2, name: 'Bombasto' },
      { id: 3, name: 'Magneta' },
      { id: 4, name: 'Tornado' },
      { id: 5, name: 'Superman'},
      { id: 6, name: 'Batman'},
      { id: 7, name: 'BatGirl'},
      { id: 8, name: 'Robin'},
      { id: 9, name: 'Flash'},
      { id: 10, name: 'Bombasto' },
      { id: 11, name: 'Magneta' },
      { id: 12, name: 'Tornado' },
      { id: 13, name: 'Windstorm' },
      { id: 14, name: 'Bombasto' },
      { id: 15, name: 'Magneta' },
      { id: 16, name: 'Tornado' },
      { id: 17, name: 'Windstorm' },
      { id: 18, name: 'Bombasto' },
      { id: 19, name: 'Magneta' },
      { id: 20, name: 'Tornado' }
    ];

    return {accounts, companies};
  }
```

**Comment by wardbell** [comment]
I don't think your workaround will work.  Teaching the in-mem service to create your in-mem datastore would complicate this library and its testing. It's probably a breaking change for the community (although I can imagine ways around _that_).

On balance, the _value-to-effort_ ratio is not presently sufficient to take this on.

Fortunately, it is easy to delay calling `resetDb` until the first HTTP request. That gives you the opportunity to prepare your data store before the in-mem web api needs it. Your preparation could be asynchronous as follows:

1. Inject your `InMemoryDbService` into your root `AppModule`.
1. call an initialization method on it such as you described above.
1. expose the promise as a property on your service
1. await that promise completion before making the first or any call to HTTP, e.g., in a "serviceReady" promise/observable that guards your application data service.

If you switch to the `HttpClient`, you can put this initialization in an `HttpInterceptor` (it's an observable pipeline) and it will all be transparent to your app.

**Comment by wardbell** [comment]
Having said that, I couldn't help looking into it. Seems like I will support both synchronous and asynchronous `createDb` results in v0.4.2 :-)
