### ISSUE TITLE
Merge in memory api in angular cli

### ISSUE THREAD

**Issue by fwd079** [angular/in-memory-web-api#118]
Hi, I don't know how to make a feature/help request in git, as this is not a big issue but more of a help request.

I'm new to Angular and started learning from Angular 2, via online tutorial. But I created my project via angular-cli and now want to add in-memory-web-api to the  project created during the tutorial, via angular-cli. How can I add new folder to go in my "build config list" please?

Can someone please guide me or point me to right direction?

Thank you in advance.

**Comment by fwd079** [comment]
Anyone?

**Comment by Foxandxss** [comment]
I created [this project](https://github.com/Foxandxss/lenguajes) to teach basic angular and testing and it is the CLI and in memory. It should serve as an example.

**Comment by fwd079** [comment]
Awesome thanks! I managed to do it myself but will definitely look at that as well. Appreciated.
Closing it.

**Comment by fwd079** [comment]
I figured it out.
