### ISSUE TITLE
GitHub releases for new versions

### ISSUE THREAD

**Issue by lharzenetter** [angular/in-memory-web-api#125]
I noticed, that there is a relaese 0.3.2 at [NPM](https://www.npmjs.com/package/angular-in-memory-web-api), but it is not mentioned [here](https://github.com/angular/in-memory-web-api/releases) as a release.

Would you mind tagging the release in GitHub also? :)

**Comment by wardbell** [comment]
Right. I haven't been keeping the tags up. Fixed it. Now I have to remember to maintain it going forward.
