### ISSUE TITLE
Config.passThruUnknownUrl: true not working

### ISSUE THREAD

**Issue by nigel-dewar** [angular/in-memory-web-api#129]
Have tried this, in app.module.ts

InMemoryWebApiModule.forRoot(FakeDbService, {delay: 0, passThruUnknownUrl: true})

But it does not work.

If I put InMemoryWebApiModule.forRoot(FuseFakeDbService, {delay: 0, Config.passThruUnknownUrl: true})

then it complains because Config doesnt fit here.

Where and how does someone configure this?

Please update your instructions on this https://github.com/angular/in-memory-web-api#passthru because it doesnt specifically say where and how to config this.

Cheers

**Comment by wardbell** [comment]
Please try
```
nMemoryWebApiModule.forRoot(FuseFakeDbService, {delay: 0, passThruUnknownUrl: true})
```

**Comment by nigel-dewar** [comment]
Hi Ward, this does work, but....

There is some work I will have to do with the security system IdentityServer4 OIDC client for Angular 2. When the callback returns a token back to the client, InMemoryWebApi module does something with it and things break.

Cheers
Nigel

**Comment by wardbell** [comment]
Maybe we can look again at this after PR #130 lands

**Comment by nigel-dewar** [comment]
No worries thanks Ward, Its not a show stopper for me, but If I figure anything Ill post it here for reference.

Love your work by the way, and I watch all your courses on PluralSight. 

cheers.
