### ISSUE TITLE
Support for multi path rest api

### ISSUE THREAD

**Issue by stephanecot** [angular/in-memory-web-api#131]
A nice addition to this wonderful api will be to support (in an easy way) multi path rest api.

By exemple:
**/api/mother/1/child/2**  or **/api/mother/2/child/2**  or **/api/mother/child/2**
==> return the same child with id = 2 (100% mocked)

Why ? Because, sometimes I have a real API like this and I don't want to have 2 separate implementations to mock my http call.
Today, if I want to call **/api/mother/1/child/2**, I need to have a second implemation and transform my url like this: **/api/child/2**

**Comment by wardbell** [comment]
I get it and that's a perfectly common, RESTy way to address that resource. It's too ambitious for this library I'm afraid but you can override the `parseUrl` method pretty easily to achieve this effect on your own. See the `src/app` example and tests that were added recently.

Sorry I have to close as we won't be proceeding with your idea. Hope you have fun and that my suggested workaround gets you out of the woods.
