### ISSUE TITLE
Set a collection in a nested endpoint which is already a collection

### ISSUE THREAD

**Issue by damsorian** [angular/in-memory-web-api#139]
Hi!

I need to set a collection in a nested endpoint which is already a collection and I don't want to take it as an ID. is there any easy way?

Something like this:
```javascript
createDb() {
  return {
    // api/heroes
    'heroes': [
      { id: 1, name: 'Windstorm' },
      { id: 2, name: 'Bombasto' },
    ],
    // api/heroes/warriors
    'heroes/warriors': [
      { id: 1, name: 'Pepe' },
      { id: 2, name: 'Grillo' },
    ],
  };
}
```

Thanks!

**Comment by wardbell** [comment]
You should be able to do that by overriding the `parseRequestUrl` in your `InMemoryDbService` to get what you want.

See [`HeroInMemDataOverrideService`](https://github.com/angular/in-memory-web-api/blob/master/src/app/hero-in-mem-data-override.service.ts) for an example of a `parseRequestUrl` override that turns `/foo/heroes` into just `/heroes`. You could do something similar to translate to a collection named `warriors` or `heroes-warriors`.

If you REALLY want to have a collection named `heroes-warriors`, you can but you'll have to play around with the result of the `ParsedRequestUrl`
