### ISSUE TITLE
Using only @angular/common/http but @angular/http still required.

### ISSUE THREAD

**Issue by Redface** [angular/in-memory-web-api#140]
Hello,

First of all, thank you for updating and supporting quickly to use this library for angular4.

I've fully replaced @angular/http with @angular/common/http(HttpClientModule),  removed @angular/http from my project.

But In-memory-web-api still requires @angular/http, I took a look inside of in-memory-web-api.d.ts and found import { XHRBackend } from '@angular/http';
Of course you allow users to user either HttpClientModule or Http but users do not want to keep Http in a project (in the future as well, it is already deprecated in angular5.beta.6 https://github.com/angular/angular/blob/master/CHANGELOG.md).

I reckon import { XHRBackend } from '@angular/http'; should only be applied when users use @angular/http only.

**Comment by wardbell** [comment]
I thought about doing that. But it was a lot of work, changed the API for many people, and didn't offer real benefit.  Remember that the in-memory web api is _only for development_ and you'd never put it into production (PLEASE!).  The simple, least intrusive thing, was to load both libraries.

You should be excluding the in-memory web api in your production builds and it won't show up.

**Comment by Redface** [comment]
@wardbell Thank you for the quick answer. Of course I do not include in-memory web into a production. I just wanted to make sure that http will be deprecated. Now I fully understand your explanation. Thank you for our update once again.

**Comment by wardbell** [comment]
Well ... you won't be the only one to ask this question. Rather than keep answering it,
I've decided to offer the setup module in both HttpClient-only and Http-only forms.

I also speak to this in the README.

It's in PR #141 and will be out in `v0.4.5`. 

Check it out and thanks for asking :-)
