### ISSUE TITLE
How to modify HTTP response Headers ?

### ISSUE THREAD

**Issue by Lelenaic** [angular/in-memory-web-api#144]
We're using JWT for authentication in our angular app.
The real back-end sends its HTTP Response with a set-cookie to define the JWT and its life-time.

![Response header](https://image.ibb.co/jkYUm5/2017_09_14.png)

However, I don't know how to/if it's possible to modify response header to add a 'Set-Cookie' header with in-memory-web-api.

Any idea please ?

**Comment by stephanecot** [comment]
You can use Angular new Interceptor to directly modify to response. No?

**Comment by wardbell** [comment]
There is an example in THIS repo in the tests: https://github.com/angular/in-memory-web-api/blob/22c2d970b4da89ba4aebe71c2ee7d73798f20ad5/src/in-mem/http-client-backend.service.spec.ts#L35-L54

**Comment by Lelenaic** [comment]
Thanks everyone, it will be perfect :D
