### ISSUE TITLE
npmjs.org package docs say to import from wrong package in app.module.ts

### ISSUE THREAD

**Issue by remkohdev** [angular/in-memory-web-api#146]
In the npm documentation to configure the @NgModule it says to 

import { HttpClientInMemoryWebApiModule } from 'http-angular-in-memory-web-api';

but I believe the export class is 'from angular-in-memory-web-api' 

Note: from http-angular... vs angular...

**Comment by wardbell** [comment]
Good catch!  Fixed in PR #147
