### ISSUE TITLE
Can I use the in-memory web api for some api calls but not for all?

### ISSUE THREAD

**Issue by lxjhk** [angular/in-memory-web-api#154]
Could I use the in-memory web api for selective apis calls based on the api endpoints?  It this possible?

**Comment by jakkn** [comment]
Sounds like you're looking for `passThruUnknownUrl: true`. It's documented in the README at [Pass thru to a live server](https://github.com/angular/in-memory-web-api#pass-thru-to-a-live-server)

**Comment by wardbell** [comment]
Yup. Closing
