### ISSUE TITLE
can not add new item when collection is empty, Error is raised

### ISSUE THREAD

**Issue by sculxp** [angular/in-memory-web-api#162]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

InMemoryDbService: can not add new item when collection is empty, Error ("id type is non-numeric or unknown. Can only generate numeric ids." ) is rasied.

## Expected behavior

can add new item when collection is empty! 

## What is the motivation / use case for changing the behavior?

If id type is non-numeric, custom id generation strategy will be provided, if not, custom id generation strategy is also needed since you can not add new item when collection is empty. Maybe it's better to assume id type is numeric when collection is empty, 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by wardbell** [comment]
I just don't think it is safe to make that assumption. You can provide a custom ID generator and control this yourself. See the README.

Closing because a workable solution is available.
