### ISSUE TITLE
How to add multiple EndPoints with multiple API bases

### ISSUE THREAD

**Issue by saicharan-etp** [angular/in-memory-web-api#201]
Suppose I have multiple end points like

1) 'api-base1/service1',
2) 'api-base2/service2'

How would i configure separate services for different api bases.

**Comment by saicharan-etp** [comment]
Thanks for the reply, but i am looking for multiple API bases. Sorry for the wrong title.

**Comment by stephanecot** [comment]
In my apps, I put the bases url in a environnement file.
"base1": "....",
"base2": "..."

In dev mode, base1 & 2 will use the same "mocked" base: /api
in prod mode, base1 & 2 will use different values.

**Comment by saicharan-etp** [comment]
Thanks, it solves my requirement for some extend.
