### ISSUE TITLE
what is new in 0.8.0?

### ISSUE THREAD

**Issue by xmlking** [angular/in-memory-web-api#227]
0.8.0 released on NPM but don't see any changes or update to changelog.

**Comment by CaerusKaru** [comment]
CHANGELOG has been updated. The only change is that this package no longer supports `@angular/http` since it's deprecated and is being removed in the next major release of Angular. Please use `@angular/common/http` if you aren't already.

**Comment by gitbreaker222** [comment]
@xmlking is this the answer you were looking for? If yes, the issue could be closed I guess :heavy_check_mark:
