### ISSUE TITLE
Add ability to query multiple keys with same name and different values

### ISSUE THREAD

**Issue by vukasin0** [angular/in-memory-web-api#23]
Goal to achieve is - fetch list of particular records but not all or single.

Proposal:

> collection?id=1&id=2&id=333

should return objects with ids:

> 1, 2 and 333

**Comment by wardbell** [comment]
We can't satisfy every possible variation but we can put you in control.

v.0.1.0 (PR #31) will let you take over processing of any (or all) requests by HTTP method name.

Note that it has a new package name: angular-in-memory-web-api (no "angular2")
