### ISSUE TITLE
Get nested property of a collection

### ISSUE THREAD

**Issue by mrgoos** [angular/in-memory-web-api#24]
Hi,
If I understand correctly, while using Angular 2 and this great tool I can only ask for a collection and ID on `put`, right?
It must be `app/[COLLECTIONNAME]/ID`. What If my real `put` request only returns an array of strings and I don't have an `id` in the schema?
For example I have this collection:
```
myCollection:  
   {
     store: 
           {items: ['item1', 'items2','item3']}
   }
```
Can it be more flexible?
How can I update `items` with `put` by using in-memory-web-api?
The need for `id` is somewhat limiting IMO.
Thanks.

**Comment by wardbell** [comment]
We can't satisfy every possible variation but we can put you in control.

v.0.1.0 (PR #31) will let you take over processing of any (or all) requests by HTTP method name.

Note that it has a new package name: angular-in-memory-web-api (no "angular2")
