### ISSUE TITLE
Support for custom / composite keys and how they map to urls

### ISSUE THREAD

**Issue by mmc41** [angular/in-memory-web-api#29]
in-memory-web-api is great but I would like some my control over how urls are translated to instances of a data array. For instance, given a url like this "/app/modules/1/instances/2" I would like in-memory-web-api to map to the shown extract of an array passed to createDb.

Notice that the data effectively has a composite key of moduleId +  moduleInstanceId and does not have an id property. All of which is not well supported by in-memory-web-api right now.

```
[
 { // Module 1, Instance 2 here:
      moduleId: "1",
      moduleInstanceId: "2",
     ... 
  },
 ...
]
```

**Comment by wardbell** [comment]
We can't satisfy every possible variation but we can put you in control.

v.0.1.0 (PR #31) will let you take over processing of any (or all)  requests by HTTP method name.

Note that it has a new package name: `angular-in-memory-web-api` (no "angular2")

**Comment by mmc41** [comment]
@wardbell Great. Could you elaborate how v.0.1.0 let me take over processing. Can't see the diff from the docs?
