### ISSUE TITLE
Need for hitting in-memory-web-api and external endpoints

### ISSUE THREAD

**Issue by kevin-madhu** [angular/in-memory-web-api#30]
I need to be able to continue using in-memory-web-api to serve mock data in development, while at the same time hit external endpoints in production without much change except for the urls. ( This is a slight variation of https://github.com/angular/in-memory-web-api/issues/15 where in-memory-web-api is registered in AppModule itself.  )

Basically I need to be able to use 2 services, one which points to the url, 'app/mock_data' and 'api.server.com/mock_data' and swap between these two in development and production.

 But currently, I'm not able to do this because I have to comment out the   `InMemoryWebApiModule.forRoot(MockData)` everytime I have to hit an external endpoint and I can't find any way to conditionally load that in the AppModule imports based on the mode. 

Now, I have seen that line in the documentation which says "swap in-memory-web-api out when you have a real api", but I don't wanna do that - because I need the front-end developers to be able to go on with their work without the need to setup of a local api.

**Comment by code1line** [comment]
Side-By-Side would be great! 👍 
Is there any workaround?

**Comment by wardbell** [comment]
Hang in there. I think I'm adding that feature in v.0.1.0 via the `InMemoryBackendConfigArgs.passThruUnknownUrl` flag.

I say "I think" because I haven't tested it yet. I just wanted to get the idea baked in.

**Comment by kevin-madhu** [comment]
Is v.0.1.0 happening soon?

**Comment by wardbell** [comment]
Yup.  I'd say today if I can get the right eyes on it.

**Comment by kevin-madhu** [comment]
Please try to to include it, I'm in real need.
Thanks a lot. :)

**Comment by wardbell** [comment]
It's merged.

**Comment by kevin-madhu** [comment]
How do I pass InMemoryBackendConfigArgs.passThruUnknownUrl?
InMemoryWebApiModule.forRoot(MockData, { passThruUnknownUrl:true }) doesn't seem to work.
I get "Unknown collection" error in console.
