### ISSUE TITLE
Difficulty with passThruUnknownUrl

### ISSUE THREAD

**Issue by kevin-madhu** [angular/in-memory-web-api#33]
I'm new to angular and all these, so I'm kinda overwhelmed with whatever is happening. Everything works fine when only mock data are being accessed when using in-memory-web-api. But when trying to use mock data as specified on https://github.com/angular/in-memory-web-api/issues/30, these errors pop up on the browser console(it's kinda lengthy).

I'm using InMemoryWebApiModule.forRoot(DepartmentData, { passThruUnknownUrl: true }).

https://gist.github.com/kevin-madhu/09f40474b2d648140f0f93d7281ee04e

**Comment by psamsotha** [comment]
I'm having similar problems. The stacktrace is pointing at `InMemoryDbService.parseId`

```
zone.js:355 Unhandled Promise rejection: Cannot read property '0' of undefined ; Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property '0' of undefined(…) TypeError: Cannot read property '0' of undefined
    at InMemoryBackendService.parseId 
```
It seems when the service can't find the collection in the in-memory db, it still tries to parse the id, passing the null collection. And the `parseId` method doesn't do any null check on the `collection` argument.

```typescript
protected handleRequest(req: Request): Observable<Response> {
  const {base, collectionName, id, resourceUrl, query} = this.parseUrl(req.url);
  // collectionName doesn't match anything in the db because it is an external endpoint
  // so `collection` is null
  const collection = this.db[collectionName];
  const reqInfo: RequestInfo = {
    req: req,
    base: base,
    collection: collection,
    collectionName: collectionName,
    headers: new Headers({ 'Content-Type': 'application/json' }),
    id: this.parseId(collection, id),  // pass null collection
    query: query,
    resourceUrl: resourceUrl
  };
}

protected parseId(collection: {id: any}[], id: string): any {
  if (!id) { return null; }
  const isNumberId =  collection[0] && typeof collection[0].id === 'number';  // ERROR!
  if (isNumberId) {
    const idNum = parseFloat(id);
    return isNaN(idNum) ? id : idNum;
  }
  return id;
}
```

You can simply fix this by null checking the `parseId` method

```typescript
protected parseId(collection: {id: any}[], id: string): any {
  if (!collection || !id) { return null; }
```

From what I tested, this should solve the problem.

Also maybe another thing you may want to consider is the use case of the interceptor method. Currently the algorithm goes

```typescript
} else if (this.inMemDbService[reqMethodName]) {
  const interceptorArgs: HttpMethodInterceptorArgs = {
    requestInfo: reqInfo,
    db: this.db,
    config: this.config,
    passThruBackend: this.passThruBackend
  };
  return this.inMemDbService[reqMethodName](interceptorArgs);
} else if (reqInfo.collection) {
  return this.collectionHandler(reqInfo);
} else if (this.passThruBackend) {
  return this.passThruBackend.createConnection(req).response;
}
```

If there is an interceptor method, the interceptor method still gets called, passing the invalid request info. Maybe you should also check for the presence of a collection

```typescript
} else if (this.inMemDbService[reqMethodName] && reqInfo.collection) {
```

**Comment by kevin-madhu** [comment]
@psamsotha If you've got the fix. Could you please correct it and try sending a PR?

**Comment by wardbell** [comment]
I agree with the ` parseId` check. But the method interceptor should be called without regard to the reqInfo.collection. In fact, it would be wrong to care because the interceptor is often needed when there is no collection. I'll merge the partial

**Comment by psamsotha** [comment]
@wardbell Thanks. I guess I was not sure as to the real purpose of the interceptor method :-)
