### ISSUE TITLE
Parse error with URL like 'response.json'

### ISSUE THREAD

**Issue by Akxe** [angular/in-memory-web-api#35]
Asking for URL like `response.json` will cause error. I tracked down this error to a [parseUrl](https://github.com/angular/in-memory-web-api/blob/master/src/in-memory-backend.service.ts#L461) 
function of InMemoryBackendService. The problem is, that the `collectionName` gets seen as `base`, and the `collectionName` then is empty, and it throws.

I tried to add slash before the URL, but it ends up with same result.
```
export class InMemoryDataService implements InMemoryDbService {
    createDb() {
        let response= {
            prop: 'string',
            ...
        }
        return {
            'response.json': response
        }
    }
}
```

**Comment by wardbell** [comment]
I suppose so. It's looking for something like `api/response.json`.  A plain `/` is simply removed before it gets to that line.

I'd welcome a PR for an improved `parseUrl`. Otherwise, please work around it on your end as we are unlikely to get around to fixing this to suit your need. It is just a demo tool.

**Comment by Akxe** [comment]
I think, that this issue shouldn't be closed, as the error is not on my part. Maybe add an label?

And also, I thing this tool is great thing for testing, and not just a demo thing for Angular 2 docs.

**Comment by psamsotha** [comment]
@Akxe One thing that I often do is to use a configuration service (or something of the like). You can have a base URL in the service that is based on the environment, maybe `/api` for development, and `/` for production. I use this alot actually, as URLs are so common in the app. Not just for use the in-memory-web-api, but for most cases, I keep the URL (or it's base) configurable by environment

**Comment by wardbell** [comment]
We can't anticipate every request url scheme. The v.0.1.6 version lets you override the `parseUrl` method with your own implementation. Have fun.
