### ISSUE TITLE
API Change: More control over request/response shape

### ISSUE THREAD

**Issue by jhuntoo** [angular/in-memory-web-api#4]
Thanks for the library, it's really handy.

I have a few suggestions for the API. Currently you have to use the /app endpoint with the name of the collection, which then responds with { data: yourCollection}. This has meant i've had to change my actual http contracts to just use a mocked api.

What about modifying the API to look something like this?

```
export class InMemoryStoreService {
  createEndpoints() {
     return [
       { match: 'api/v1/events', responsebody: { events: [ { id: 1, foo: 'bar'}]} }
     ]
  }
}
```

This would satisfy my initial needs, but eventually it could be expanded to satisfy more complicated scenarios with proper routing, parameters, headers etc.

Not sure if this is beyond the scope of this project, however I think the above suggestion would at least allow users of this library to not drastically modify their http contracts when building an app that will later call a real API.

Thoughts?

**Comment by wardbell** [comment]
We can't satisfy every possible variation but we can put you in control.

v.0.1.0 (PR #31) will let you take over processing of any (or all)  requests by HTTP method name.

Note that it has a new package name: `angular-in-memory-web-api` (no "angular2")
