### ISSUE TITLE
Strange lint warnings about missing C:/github/angular.in-memory-web-api/src//src/index.ts

### ISSUE THREAD

**Issue by mmc41** [angular/in-memory-web-api#43]
If I switch to this new in-memory-web-api library, I get a strange lint warning when running "ng test" on my mac:

```
WARNING in ./~/angular-in-memory-web-api/index.js
Cannot find source file 'C:/github/angular.in-memory-web-api/src//src/index.ts': Error: Can't resolve './C:/github/angular.in-memory-web-api/src//src/index.ts' in '/Users/xxx/mytestproject/node_modules/angular-in-memory-web-api'
 @ ./src/app/shared/services/test.service.spec.ts 6:34-70
 @ ./src \.spec\.ts
 @ ./src/test.ts

```

The source file that it can not find is "C:/github/angular.in-memory-web-api/src//src/index.ts" and is unrelated to my project and even my platform (I am using Mac - not windows).

**Comment by wardbell** [comment]
Works on our machines. Please provide a repro. Make sure you've deleted the only package and installed the new in node_modules

**Comment by mmc41** [comment]
Here is a reproducible hello-world sized example. Unzip, "npm install" and "ng test" on a Mac to reproduce. You might also be able to reproduce on a PC (not sure) but in this case you need to make sure you have folder on it called "C:/github/angular.in-memory-web-api" !!

[bugdemoproject.zip](https://github.com/angular/in-memory-web-api/files/515508/bugdemoproject.zip)

**Comment by wardbell** [comment]
You have some kind of loader problem that I can't see. I'm not using the CLI so I personally don't know how to configure it properly. Something is clearly wrong if your app is looking for `../src//src/...`. 

This looks like a compile problem not a lint problem. But what do I know?

**Comment by mmc41** [comment]
Are you sure, it is not because there is something wrong with your npm package as this is the only package that the angular cli tools complain about. The bug demo project is produced by "ng new" with just a few additions. If you are sure, I can report a bug with the "ng tools instead" ?

**Comment by mmc41** [comment]
Just to emphasise, I am using a standard out-of-the-box configuration produced by the angular cli tools. If it is reproducible on your machine (i.e. not something about nodejs local to my machine) than it is strange that the problem only happens with your npm package I think.

**Comment by ilios-galil** [comment]
Looks like the `.` typo is in all the map files in the `node_modules/angular-in-memory-web-api` folder. I think it should be a `-` and there is also that `C:/`, I am not sure it should be there (since i'm on a mac), but i'm new to npm so I don't want to say something wrong.

**Comment by mmc41** [comment]
@wardbell I can also reproduce this problem using the new version 0.1.9. I have no idea how to fix it myself so I would highly appreciate a fix.... Where you able to reproduce the problem in bugdemoproject.zip on your machine or do you need more info from me here ?

**Comment by wardbell** [comment]
I'm sorry but this project has not been vetted with the CLI and the tiny team on this repo doesn't have resources at the moment to square with the CLI.  Maybe you can cross-reference this with an issue on the CLI repo so that someone on that much larger team can help.

**Comment by jlutz777** [comment]
I think @igalil is on to the problem. I am running into the same thing when using webpack because the sourcemaps have hard coded values. Look, for example, at http-status-codes.js.map and you'll see a hardcoded value of 'C:/github/...'. I believe sourceRoot in tsconfig.json needs to be updated to not be ./src. For now to work around the problem, I'm just excluding the project for webpack so it avoids the errors.

**Comment by nqcuong72** [comment]
I have this problem with webpack. Please help.

**Comment by nqcuong72** [comment]
I have fixed it by adding to exclude session of 'webpack.test.js':
          exclude: [
            // these packages have problems with their sourcemaps
            helpers.root('node_modules/angular-in-memory-web-api'),
            ....
