### ISSUE TITLE
Example of how to use HTTP method interceptors for documentation / avoiding errors=

### ISSUE THREAD

**Issue by mmc41** [angular/in-memory-web-api#44]
I am not sure how to use the new HTTP method interceptors (or what they do) and noticed some other people getting errors because they apparently used it wrong. Could you provide an example so it is much clear (and to avoid getting to many issues from people using it wrong) ?

**Comment by wardbell** [comment]
See the new file, `examples/hero-data.service.ts`, added as part of v.0.1.6. See brief description in the README under "examples".
