### ISSUE TITLE
Any plan to support pagination?

### ISSUE THREAD

**Issue by itryan** [angular/in-memory-web-api#45]
Currently `/api/models` returns the whole collection by default, is there any plan to support pagination via something like `/api/models?start=100&limit=50`, while `start` and `limit` can be customized via `InMemoryBackendConfig`?

**Comment by wardbell** [comment]
No. This is a demo tool. You can do this yourself by overriding the GET method handling as described in the README

**Comment by itryan** [comment]
@wardbell thanks for your guidance, now I managed to make the pagination work.

**Comment by alinaalam** [comment]
@itryan how did you achieve it?

**Comment by alinaalam** [comment]
@wardbell I am trying to achieve the same result. This is so far what I have been able to achieved:

I have a service:
getMaterialItems(): Observable<MaterialItem[]> {
        let url = `${this.materialsUrl}?page=1&items=8`;
        return this.http.get<MaterialItem[]>(url);
    }
and I have an overridden method:
/**
     * HTTP GET Interceptor
     * We're overriding this method to incorporate pagination
     */ 
    get(reqInfo: RequestInfo) {
        const collectionName = reqInfo.collectionName;
        let page = (reqInfo.query['page']) ? reqInfo.query['page'] : 1;
        let items = (reqInfo.query['items']) ? reqInfo.query['items'] : 8;
        let materials = reqInfo.utils.getDb();
        // need to implement pagination here
        return reqInfo.utils.createResponse$(() => {
             const data = materials;
             const options: ResponseOptions = {
                 body: data,
                 status: STATUS.OK
             };
             return this.finishOptions(options, reqInfo);
         })
    }
    
    /////////// helpers ///////////////
    private finishOptions(options: ResponseOptions, {headers, url}: RequestInfo) {
        options.statusText = getStatusText(options.status);
        options.headers = headers;
        options.url = url;
        return options;
    }

I get the result correctly in this overridden method, but when I try to console the returned response in my service, I get an object with the following properties: _isScalar, forEach, subscribe, promise
I am unable to get my response from this object

**Comment by svenkeeter** [comment]
@itryan Can you please share the code on how to make pagination work?

**Comment by jesusmariajurado** [comment]
@svenkeeter you can find how heros db is overrided in src/app/hero-in-mem-data-override.service.ts by villains db. You might find out how getVillians method works and then implement your pagination logic there.

This could be an example:

`if(reqInfo.req.params.has('page')){
         let page = reqInfo.req.params.get('page');
         let limit = reqInfo.req.params.has('limit') ? reqInfo.req.params.get('limit') : 10;
         console.log('PAGE is ' + page + ' LIMIT is ' + limit);
         data = this.myCollection.slice(limit * (page - 1), limit * page);
}
`
