### ISSUE TITLE
Error: unable to parse url '/config'; original error: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by jbeckton** [angular/in-memory-web-api#46]
This is my second attempt to use in memory web api. We have some http calls that I do not want to go to the in memory api, one of them just so happens to be /config. 

I added the passThruUnknownUrl: true  " InMemoryWebApiModule.forRoot(CGSData, {passThruUnknownUrl: true } )"

**Comment by jbeckton** [comment]
After some debugging it seems like this module does not work with relative urls. In some of our http calls back to the hosting app we just use "/foo", Angular http is smart enough to prefix that with the current location host "localhost:3000" or "myapp.com". There is no point in trying to somehow configure a hostname per environment when the http call url is back to the same host that loaded the angular app.

**Comment by psamsotha** [comment]
Probably a dup of #35

**Comment by wardbell** [comment]
We can't anticipate every request url scheme. The v.0.1.6 version lets you override the `parseUrl` method with your own implementation. Have fun.
