### ISSUE TITLE
Please avoid calling delay on Observable stream if delay==0 to make async  tests work

### ISSUE THREAD

**Issue by mmc41** [angular/in-memory-web-api#47]
As the angular2 async test support does not work with Observable streams calling setInterval, it would be great if in-memory-web-api did not call the delay method if delay == 0. Than at least one can easily unit test code using  in-memory-web-api in that case.

**Comment by wardbell** [comment]
Excellent idea. Done in next release (v.0.1.6). You set to 0 explicitly else default 500ms delay.
