### ISSUE TITLE
From angular2-in-memory-web-api to angular-in-memory-web-api

### ISSUE THREAD

**Issue by pmcalabrese** [angular/in-memory-web-api#48]
I have a angular-cli bootstrapped project.  I had angular2-in-memory-web-api, everything was working as expected. Then i decided to upgrade and use the newest version *angular-in-memory-web-api* but unfortunately i get the following error (basically my api route `/api/whatever` does not exist)

![image](https://cloud.githubusercontent.com/assets/1509241/19223665/a3e899c0-8e75-11e6-8ffd-c3cc807a1bfb.png)

Any suggestions? and any reason why this upgrade is braking?

**Comment by wardbell** [comment]
Not enough information to answer. I can only assure you that all apps known to us (including all doc samples) are working fine and that all functional changes were additions. You'll have to compare what is different between your old and new app. Look at package.json and inspect node_modules to see that it conforms. Look at your ES import statements. Look for all mentions in your app of `angular2-in...` ... there should be NONE.

**Comment by pmcalabrese** [comment]
@wardbell Thx. I can provide more information, absolutely no problem. I can ensure that there are no other mentions of `angular2-in-memory-web-api`.

I simply switched from `angular2-in-memory-web-api` to `angular-in-memory-web-api` and it's not working anymore. Can you point me an app bootstrapped with angular-cli that use angular-in-memory-web-api?

**Comment by wardbell** [comment]
I don't use the CLI, sorry. Not yet. But I see no reason why that should matter. All of the documentation samples use the `angular-in-memory-web-api`. Please review them.

**Comment by mentlsve** [comment]
@pmcalabrese One explanation for your output could be that `HttpModule` is imported after `InMemoryWebApiModule.forRoot(InMemoryDataService)`. In this case you try to call the "real" API endpoint which does not exist. 

> Always import the InMemoryWebApiModule after the HttpModule to ensure that the XHRBackend provider of the InMemoryWebApiModule supersedes all others.

**Comment by wardbell** [comment]
Closing as old and not reproducible. @mentlsve may have provided your answer.
