### ISSUE TITLE
InMemoryBackendService class should <T>

### ISSUE THREAD

**Issue by SamuelMarks** [angular/in-memory-web-api#59]
IMHO then we can do this do the `class`:
```
protected findById(collection: T[], id: number | string): T;
protected genId(collection: T): T;
protected indexOf(collection: T[], id: number): number;
protected parseId(collection: {id: T;}[], id: string): T;
protected removeById(collection: T[], id: number): boolean;
```

I can make all these changes and send it off in a PR, but writing this issue to see if you'd want/accept that.

**Comment by wardbell** [comment]
I don't see the point of typing. These methods make no assumption about the collection other than that it has an `id` property which itself may be of any type. Sorry. Closing.
