### ISSUE TITLE
Ionic 2 - No tsconfig.json in node modules folder of angular-in-memory-web-api

### ISSUE THREAD

**Issue by bkode** [angular/in-memory-web-api#60]
**Please help**

Tried following the steps in #42 but after installing with npm i angular-in-memory-web-api the folder of angular-in-memory-web-api in node-modules doesn't contain a tsconfig.json.

**Comment by wardbell** [comment]
Nor should it. Libraries like this one do not include such files. Look at @angular packages for example.
