### ISSUE TITLE
Not assigning returned API data to `data` property?

### ISSUE THREAD

**Issue by chrisnicola** [angular/in-memory-web-api#61]
There does not seem to be a simple way to override the `data` property of returned API data. My API doesn't wrap the returned data in a object property in this way.

I could use overrides but that seems more involved than necessary for such a minor change, or is it? Maybe I'm just misunderstanding this.

**Comment by wardbell** [comment]
I agree. Added `responseInterceptor` to new v.0.1.14 in commit https://github.com/angular/in-memory-web-api/commit/e423d571795782e8862e00703de2ee32c9a017f1

Example in `example/hero-data.service.ts`:
```
 // intercept response from the default HTTP method handlers
  responseInterceptor(response: ResponseOptions, reqInfo: RequestInfo) {
    const method = RequestMethod[reqInfo.req.method].toUpperCase();
    const body = JSON.stringify(response.body);
    console.log(`responseInterceptor: ${method} ${reqInfo.req.url}: \n${body}`);
    return response;
  }
```
