### ISSUE TITLE
in-memory-web-api returns html

### ISSUE THREAD

**Issue by makafsal** [angular/in-memory-web-api#63]
In-memory-web-api returns html instead of dummy data.

**Comment by psamsotha** [comment]
Can you show your configuration (how you configure the in-memory module) and also your mock data.

**Comment by makafsal** [comment]
Yeah, that was the problem. 
But it was not same as in your case.

Seeing the below code, I thought HttpModule gets loaded first. But somehow it did not happen(Dunno why!)
```
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot(ROUTES, { useHash: true })
  ],
```

This is how I solved the problem:
I changed the following code to the second snippet.

```
    imports: [
        FormsModule,
        CommonModule,
        ModalModule,
        RouterModule.forChild(routes),
        InMemoryWebApiModule.forRoot(DepartmentData)
        ],
```

```
    imports: [
        **HttpModule**,
        FormsModule,
        CommonModule,
        ModalModule,
        RouterModule.forChild(routes),
        InMemoryWebApiModule.forRoot(DepartmentData)
        ],
```
