### ISSUE TITLE
0 cannot be used as an id

### ISSUE THREAD

**Issue by jlutz777** [angular/in-memory-web-api#66]
Because several checks in the code use !id as the check, a value of 0 comes back as a falsy value, thus breaking things. It seems to me that an id with value 0 should be valid. I believe there are three locations in code that would be needed to fix this. I happened to run into it with a post and a delete.

As a test, simply set the db to an initial value of:
[
    {
      "id": 0,
      "otherdata": "my value"
    },
    {
      "id": 1,
      "otherdata": "my other value"
    }
]

Then, try to do a post or delete of the item with id 0.

**Comment by wardbell** [comment]
Agreed. Fixing for v.0.2.0 PR #79

**Comment by jlutz777** [comment]
@wardbell Thanks for the quick fix!  I noticed with this fix that an id of empty string falls into the same category as 0, rather than undefined or null. So basically I post an object with id of empty string, and it doesn't get an id automatically generated. Is this functioning as you expect? Thanks again!

**Comment by wardbell** [comment]
Yes, I believe that is my intention.  If you specify the `id`, it will take what you specify.
