### ISSUE TITLE
[Suggestion] - change rootPath in InMemoryBackendConfigArgs to be array of paths

### ISSUE THREAD

**Issue by vukasin0** [angular/in-memory-web-api#69]
Use case:

Api is scoped so scope is part of `rootPath`.

```
/api/v2/auth/users
/api/v2/auth/oauth

/api/v2/carparts/wheels
/api/v2/carparts/dors
/api/v2/carparts/keys

rootPath = /api/v2/carparts
collections = {wheels, dors, keys}
```

Web Api is configured on `CarPartsModule`.

All calls to `/api/v2/auth` will `passTrough` if it is configured.

If we have multiple rootPaths we can mock calls outside of current scope - here `carparts`.

Cons:
it is possible to have same named endpoints(collections) across scopes:
```
/api/v2/carparts/keys
/api/v2/security/keys
```

**Comment by wardbell** [comment]
Please try the `parseUrl` override feature which is there so you can convert your own scheme into  the `ParsedUrl` structure that the in-mem-web-api service needs.

If that doesn't work for you, please open a new issue with the specifics. A repro would be good.
