### ISSUE TITLE
Map file lookup fails

### ISSUE THREAD

**Issue by dev6andrew** [angular/in-memory-web-api#7]
The output `.js` files have references to `.js.map` files that are not being checked into the repo. This is throwing warnings when trying to consume the module.

**Comment by RobCannon** [comment]
I tried to get a pull request together to fix this, but I don't see where the build process updates the files in the repository.  If the output files were just manually copied from the in-memory-web-api directory to the root of the repository, the .map file would have the wrong path to the source files.

I think the build process need to be changed to generate the output in the root (and the clean step could go away), but I don't want to break the publishing workflow.

**Comment by wardbell** [comment]
we'll  fix it

**Comment by sky-coding** [comment]
when?

**Comment by Judahh** [comment]
Nothing yet?

**Comment by alvaromuir** [comment]
Until then, how can we manually address this?

**Comment by wardbell** [comment]
It is now in v.0.0.21
