### ISSUE TITLE
A URL without a collection name will crash. Even with passThruUnknownUrl

### ISSUE THREAD

**Issue by jsgoupil** [angular/in-memory-web-api#73]
With the `passThruUnknownUrl`, I expect that any URL that the package receives that does not know should be simply passed through. However, a URL without a `collectionname` will fail.

Something like "http://myurl/path" (without a /collectionname) will fail.

Problem here:  
https://github.com/angular/in-memory-web-api/blob/master/src/in-memory-backend.service.ts#L538

    [collectionName] = collectionName.split('.');

**Comment by wardbell** [comment]
Thanks for identifying the potential for an exception there. PR #79 fixes that.

But you seem to want something else ... you want unknown URLs to be passed through to the server (which, I assume, you have running and ready to receive the request). You can do that as the ReadMe  tells you w/r/t `passThruUnknownUrl:boolean`

It's `false` by default; set it `true` and this service will attempt to create the runtime `XHRBackend` and pass your request through to it.

If your real interest is in a different URL scheme for your API, the ReadMe explains how you can replace the default `parseUrl` method.

The PR #79 adds a new configuration option - `apiBase` - gives you a bit more flexibility in controlling the path to your api routes (e.g., no path, a one segment path (today's default), or n-segments). See the updated ReadMe for that PR.
