### ISSUE TITLE
Unexpected behavior due to bad handling of overridden responseInterceptor

### ISSUE THREAD

**Issue by mbj79** [angular/in-memory-web-api#75]
If the `InMemoryDbService` class has a `responseInterceptor` function, `InMemoryBackendService` currently copies that function to its own `responseInterceptor` variable, and then uses that variable to call the function while processing requests. 

This leads to unexpected behavior, because the function gets executed with the `this` variable set to the `InMemoryBackendService` instead of the `InMemoryDbService` (verify by calling `console.log(this)` from your `responseInterceptor`). Any code that uses `this` inside the overridden `responseInterceptor` to reference other variables or functions in the `InMemoryDbService` class will fail.

**Comment by wardbell** [comment]
Closed by PR #79
