### ISSUE TITLE
[Feature Request] Support for nested resources

### ISSUE THREAD

**Issue by scottescue** [angular/in-memory-web-api#77]
As best I can tell, there's currently no support for nested resources.  Nested resources are relatively common in the REST APIs I've used. For example, I might have an API that provides banking account information by exposing the resource endpoints shown below.  
```
https://myservice.com/accounts
https://myservice.com/accounts/1/transactions
```

The first is a top-level resource that retrieves basic information for all accounts.  The second is a nested resource that retrieves transaction details for a specific account.  I don't believe there's a way to support this second, nested resource using the in-memory-web-api.

I would be glad to work up a Pull Request if you're interested in adding this feature.  I've overridden `parseUrl` in my app to identify fully qualified collection names for nested resources.  For example, parsing a request to the transactions endpoint shown above would result in a collection name of 'accounts/1/transactions'.  The hash I return from `createDb' then must contain a collection key of the same name.

**Comment by wardbell** [comment]
There is not support for nested resources. We regret that we won't be adding such support, even if someone (like you) is kind enough to supply an implementation.

There are too many possible implementations. Are `transactions` a nested object within `accounts` or are they in a different collection related by a foreign key. What's the property name for that FK? What about delete, insert, update? Does order matter. It never stops.  And someone is bound to be disappointed, leading to more options and more complexity.

This project exists primarily to support the Angular documentation samples. It is wonderful that so many people also find it useful for their development. But we can only go so far in catering to everyone's needs given our available resources and the purpose of this project.

Fortunately, you can override both the `parseUrl` method and the implementations of any of the HTTP methods. The ReadMe describes how.

Thanks for giving this project a try.
