### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by balajibk5** [angular/in-memory-web-api#83]
why should i use this in-memory-web-api

**Comment by Foxandxss** [comment]
That is a good question. If you don't know why, you don't need to use it.

**Comment by jesselpalmer** [comment]
Good point by @Foxandxss. @balajibk5 it's mainly used in the angular tutorials on [angular.io](angular.io).

**Comment by wardbell** [comment]
It's primarily useful in development when/if you either don't want to set up a server or the existing remote web api does not (yet) support your application requirements.
