### ISSUE TITLE
how to install this package ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [angular/in-memory-web-api#88]
```sh
$ npm i -S in-memory-web-api
```

**Comment by xgqfrms-GitHub** [comment]
**stupid docs!**

<del>``` $ npm i -S in-memory-web-api ``` </del>

```sh
$ npm i angular2-in-memory-web-api
```

**Comment by xgqfrms-GitHub** [comment]
https://github.com/angular/quickstart/blob/master/package.json  
```sh
"angular-in-memory-web-api": "~0.2.4", 
``` 
![npm i -s angular-in-memory-web-api](https://cloud.githubusercontent.com/assets/18028768/21760006/bdbe6c20-d683-11e6-80bb-f120da213761.png)
# updating ??? 👎

**Comment by filipesilva** [comment]
You were looking at the wrong package on npmjs.com.

The right one is https://www.npmjs.com/package/angular-in-memory-web-api
