### ISSUE TITLE
Provide a reference to InMemoryBackendService on function overrides

### ISSUE THREAD

**Issue by cgatian** [angular/in-memory-web-api#90]
If a method of the InMemoryBackendService is overridden, such as `get`.  In the arguments to the function provide a way to to invoke the InMemoryBackendService `collectionHandler`.

This will allow overridden methods the contain logic whether to return their own `Observer<Response>` or defer to the `InMemoryBackendService`.

This is a terrible representation of what I'm suggesting, but hopefully it gets the point across.

**Within `handleRequest`**
```
try {
      if ('commands' === reqInfo.base.toLowerCase()) {
        return this.commands(reqInfo);

      } else if (this.inMemDbService[reqMethodName]) {
          // omitted for brevity 
        return this.inMemDbService[reqMethodName]({ 
                ...interceptorArgs,
                defaultHandler: this.defaultResponseHandler
         });
      } else {
         this.defaultResponseHandler();
      }    
```

Perhaps there's a better approach.  Currently, I do not see a way of intercepting the `get` and conditionally providing a response.

**Comment by wardbell** [comment]
My immediate reaction is that we're overthinking it. If you need to take over an HTTP method, then you take it over. I made some parsing methods available but to turn around and delegate back to the default behavior? Why? OK, I can imagine some use cases but none of them are compelling enough (yet) for me to add this feature. 

And if you really want to do that, you can sub-class the `InMemoryBackendService` itself and take it from there.

Closing for now,

**Comment by cgatian** [comment]
I very well could be overthinking it...

There are two situations I could see:
1) My immediate reason I require this is to do authentication.  The POST data consists of a user/password and should return a User object. 

2) Some endpoints require streams of file data.  GET `/document/1&type=pdf`.

It seems reasonable to be able to call back to the `InMemoryBackendService` to allow it to handle the request.  Am I overthinking this?

**Comment by mak962753** [comment]
for the authentication case it's probably possible to create 'auth' collection and provide the responseInterceptor implementation...
